auto-assignee:
  choose:
    part:
      number-changes-merge-request-files:
        coefficient: '1'
        enable: 'false'
      minimize-count-review:
        coefficient: '1'
        enable: 'true'
  excluded:
    part:
      max-merge-request-per-reviewer:
        enable: 'true'
      review-task-branch:
        enable: 'true'
      exclude-author:
        enable: 'true'

git:
  lab:
    api:
      url: ${GITLAB_URL}
      token: ${GITLAB_TOKEN}
      username: ${GITLAB_USERNAME}
  repo:
    path: ${GIT_REPO_PATH}

spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: 'true'
  datasource:
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
    username: ${postgres.username}
    url: jdbc:postgresql://${postgres.host}:${postgres.port:5432}/${postgres.db-name:dr}
  redis:
    host: ${redis.host}
    port: ${redis.port}
  banner:
    location: banner.txt
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org.hibernate.sql: DEBUG
#    org.hibernate.type: TRACE
